create index if not exists libraries_search_document_idx on libraries using gin (search_document);
create index if not exists chunks_search_document_idx on chunks using gin (search_document);
create index if not exists chunks_embedding_idx on chunks using hnsw (embedding vector_cosine_ops);
create index if not exists source_documents_version_kind_idx on source_documents(version_id, source_kind, source_priority);
create index if not exists source_documents_canonical_url_idx on source_documents(version_id, md5(coalesce(canonical_url, '')));
create index if not exists chunks_source_document_idx on chunks(source_document_id);
create index if not exists chunks_version_path_idx on chunks (version_id, path);
alter table chunks add column if not exists content_sha text;
create index if not exists chunks_content_sha_idx on chunks(content_sha);
create index if not exists source_sections_version_path_idx on source_sections(version_id, path, start_line);
create index if not exists source_sections_document_idx on source_sections(source_document_id);
create index if not exists source_sections_search_idx on source_sections using gin(search_document);
create index if not exists context_snippets_version_role_idx on context_snippets(version_id, role, path);
create index if not exists context_snippets_section_idx on context_snippets(source_section_id);
create index if not exists context_snippets_chunk_idx on context_snippets(primary_chunk_id);
create index if not exists context_snippets_search_idx on context_snippets using gin(search_document);
create index if not exists context_snippets_entities_idx on context_snippets using gin(entities);
create index if not exists context_snippets_task_tags_idx on context_snippets using gin(task_tags);

create index if not exists agent_operations_version_kind_idx on agent_operations(version_id, operation_kind, product);
create index if not exists agent_operations_search_idx on agent_operations using gin(search_document);
create index if not exists agent_operations_source_chunks_idx on agent_operations using gin(source_chunk_ids);
create index if not exists agent_operations_embedding_idx on agent_operations using hnsw (embedding vector_cosine_ops);
create index if not exists agent_operation_examples_version_language_idx on agent_operation_examples(version_id, language, product);
create index if not exists agent_operation_examples_search_idx on agent_operation_examples using gin(search_document);
create index if not exists agent_recipes_version_kind_idx on agent_recipes(version_id, task_kind, product);
create index if not exists agent_recipes_search_idx on agent_recipes using gin(search_document);
create index if not exists agent_recipes_source_chunks_idx on agent_recipes using gin(source_chunk_ids);
create index if not exists agent_recipes_embedding_idx on agent_recipes using hnsw (embedding vector_cosine_ops);
create index if not exists library_versions_library_version_idx on library_versions (library_id, version);
create index if not exists refs_library_channel_idx on refs (library_id, channel);
create index if not exists index_requests_status_updated_idx on index_requests (status, updated_at desc);
create index if not exists telemetry_events_event_created_idx on telemetry_events (event, created_at desc);
create index if not exists suggest_logs_cache_idx on suggest_logs (query_hash, fingerprint_hash, created_at desc);
