-- Retired in indexing v2.
-- agent_operations and agent_operation_examples were broad inferred surfaces.
-- Migration 025 replaces them with api_operations, sdk_methods, code_examples,
-- and agent_recipes.
